# Generated by Django 3.1.7 on 2021-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(default='Hrithik', max_length=64),
            preserve_default=False,
        ),
    ]
